apiVersion: scaffolder.backstage.io/v1beta3
# https://backstage.io/docs/features/software-catalog/descriptor-format#kind-template
kind: Template
metadata:
  name: exampo3-cobble-template
  title: exampo3 Cobble Template
  description: An example template that cobbles
spec:
  owner: user:guest
  type: service

  # These parameters are used to generate the input form in the frontend, and are
  # used to gather input data for the execution of the template.
  parameters:
  
    ## This does NOT work... (array element indicator, "-," inside the file, i.e., $yaml key repeated in same object) // reason: object must have unique keys
    # $yaml: ./step1.yaml 
    # $yaml: ./step2.yaml

    ## This works... (array element indicator, "-," outside the file, i.e., $yaml in separate array slots)
    - $yaml: ./step1.yaml
    - $yaml: ./step2.yaml

    ## This works... ($yaml nested in separate objects)
    # - title: Cobble in some steps
    #   required:
    #     - name
    #   properties:
    #     $yaml: ./prop1.yaml
        
    # - title: Cobble a location
    #   required:
    #     - repoUrl
    #   properties:
    #     $yaml: ./prop2.yaml

  steps:
    # Each step executes an action, in this case one templates files into the working directory.
    - id: fetch-base
      name: Fetch Base
      action: fetch:template
